# Generated by Django 3.2.18 on 2023-04-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
