# Generated by Django 3.2.18 on 2023-03-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='license_code',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
