# Generated by Django 3.2.18 on 2023-04-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_auto_20230406_1403'),
        ('books', '0003_auto_20230406_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='other_authors',
            field=models.ManyToManyField(null=True, related_name='other_author', to='author.Author'),
        ),
    ]
